## Underglow settings
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_SPI=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=175
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=60

## Bluetooth settings
CONFIG_ZMK_SLEEP=y # Set sleep timeout to 30 s (30*1000 ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000

## Keyboard settings
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

CONFIG_ZMK_POINTING=y
